version: "3.7"

services:
    mosquitto-hub:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto-hub
        restart: unless-stopped
        networks:
            - mosquitto
        env_file:
            - ./env/mosquitto-hub.env
        volumes:
            - ./conf/mosquitto-hub/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data/mosquitto-hub:/mosquitto/data
            - ./logs/mosquitto-hub:/mosquitto/log

    mosquitto-trust:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto-trust
        depends_on:
            - mosquitto-hub
        restart: unless-stopped
        networks:
            - default
            - mosquitto
        env_file:
            - ./env/mosquitto-trust.env
        volumes:
            - ./conf/mosquitto-trust/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data/mosquitto-trust:/mosquitto/data
            - ./logs/mosquitto-trust:/mosquitto/log

    mosquitto-public:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto-public
        depends_on:
            - mosquitto-hub
        restart: unless-stopped
        networks:
            - default
            - mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        env_file:
            - ./env/mosquitto-public.env
        volumes:
            - ./conf/mosquitto-public/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./conf/mosquitto-public/acl_file:/mosquitto/config/acl_file
            - ./data/mosquitto-public:/mosquitto/data
            - ./logs/mosquitto-public:/mosquitto/log

    grafana:
        image: grafana/grafana
        depends_on:
            - influxdb
        restart: unless-stopped
        networks:
            - default
        env_file:
            - ./env/grafana.env
        environment:
            - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
        volumes:
            - ./data/grafana:/var/lib/grafana

    homeassistant:
        image: homeassistant/home-assistant
        depends_on:
            - mosquitto-trust
            - influxdb
        restart: unless-stopped
        networks:
            - default
        ports:
            - "8123:8123"
        env_file:
            - ./env/homeassistant.env
        volumes:
            - ./data/home-assistant:/config
            - /etc/localtime:/etc/localtime:ro

    influxdb:
        image: influxdb
        restart: unless-stopped
        networks:
            - default
        ports:
            - "8086:8086"
            - "8083:8083"
            - "2003:2003"
        env_file:
            - ./env/influxdb.env
        volumes:
            - ./conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - ./data/influxdb:/var/lib/influxdb

    nodered:
        image: tyisi/node-red-docker-bootstrap
        depends_on:
            - mosquitto-trust
        restart: unless-stopped
        networks:
            - default
        ports:
            - "1880:1880"
        env_file:
            - ./env/nodered.env
        volumes:
            - ./conf/nodered:/bootstrap/conf/
            - ./data/nodered:/data

    portainer:
        image: portainer/portainer
        restart: unless-stopped
        networks:
            - default
        ports:
            - "9000:9000"
        env_file:
            - ./env/portainer.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data

    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: unless-stopped
        networks:
            - default
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    sergeant:
        image: vanhack/smartspace-sergeant
        depends_on:
            - mosquitto-trust
        restart: unless-stopped
        networks:
            - default
        env_file:
            - ./env/sergeant.env

    isvhsopen-monitor:
        image: tyisi/url-to-mqtt
        depends_on:
            - mosquitto-trust
        restart: unless-stopped
        networks:
            - default
        env_file:
            - ./env/isvhsopen-monitor.env

    laserbusy-monitor:
        image: tyisi/url-to-mqtt
        depends_on:
            - mosquitto-trust
        restart: unless-stopped
        networks:
            - default
        env_file:
            - ./env/laserbusy-monitor.env

    sip-monitor:
        image: tyisi/sip-to-mqtt
        depends_on:
            - mosquitto-trust
        restart: unless-stopped
        networks:
            - default
        ports:
            - "5060:5060"
        env_file:
            - ./env/sip-monitor.env

    spacebus:
        image: vanhack/spacebus:latest
        depends_on:
            - mosquitto-public
        restart: unless-stopped
        networks:
            - default
        env_file:
            - ./env/spacebus.env
        volumes:
            - ./conf/spacebus/config.json:/usr/share/nginx/html/config.json:ro

    mask-status-page:
        image: vanhack/mqtt-status-page:latest
        depends_on:
            - mosquitto-public
        restart: unless-stopped
        networks:
            - default
        env_file:
            - ./env/mask-status-page.env
        volumes:
            - ./conf/mask-status-page/config.json:/usr/share/nginx/html/config.json:ro

    easyappointments-mask-monitor:
        image: vanhack/easyappointments-category-monitor
        depends_on:
            - mosquitto-trust
        restart: unless-stopped
        networks:
            - default
        volumes:
            - ./conf/easyappointments-mask-monitor/config.json:/app/config.json:ro

networks:
    default:
        driver: bridge
    mosquitto:
        driver: bridge

secrets:
    grafana_admin_password:
        file: ./secrets/grafana-admin-password
