version: "3.7"
services:
    homeassistant:
        image: homeassistant/home-assistant
        env_file:
            - ./env/homeassistant.env
        network_mode: bridge
        links:
            - mosquitto:mosquitto
        ports:
            - "8123:8123"
        restart: always
        volumes:
            - /var/containers/vhs-smartspace/data/home-assistant:/config
            - /etc/localtime:/etc/localtime:ro

    mosquitto-hub:
        image: eclipse-mosquitto
        env_file:
            - ./env/mosquitto-hub.env
        network_mode: bridge
        volumes:
            - /var/containers/vhs-smartspace/conf/mosquitto-hub/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - /var/containers/vhs-smartspace/data/mosquitto-hub:/mosquitto/data
            - /var/containers/vhs-smartspace/logs/mosquitto-hub:/mosquitto/log

    mosquitto-trust:
        image: eclipse-mosquitto
        env_file:
            - ./env/mosquitto-trust.env
        network_mode: bridge
        links:
            - mosquitto-hub:mosquitto-hub
        ports:
            - "2883:1883"
            - "2901:9001"
        volumes:
            - /var/containers/vhs-smartspace/conf/mosquitto-trust/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - /var/containers/vhs-smartspace/data/mosquitto-trust:/mosquitto/data
            - /var/containers/vhs-smartspace/logs/mosquitto-trust:/mosquitto/log

    mosquitto:
        image: eclipse-mosquitto
        env_file:
            - ./env/mosquitto.env
        network_mode: bridge
        links:
            - mosquitto-hub:mosquitto-hub
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - /var/containers/vhs-smartspace/conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - /var/containers/vhs-smartspace/data/mosquitto:/mosquitto/data
            - /var/containers/vhs-smartspace/logs/mosquitto:/mosquitto/log

    influxdb:
        image: influxdb
        env_file:
            - ./env/influxdb.env
        network_mode: bridge
        ports:
            - "8086:8086"
            - "8083:8083"
            - "2003:2003"
        volumes:
            - /var/containers/vhs-smartspace/conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - /var/containers/vhs-smartspace/data/influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana
        env_file:
            - ./env/grafana.env
        environment:
            - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
        network_mode: bridge
        links:
            - influxdb:influxdb
        volumes:
            - /var/containers/vhs-smartspace/data/grafana:/var/lib/grafana

    nodered:
        image: tyisi/node-red-docker-bootstrap
        env_file:
            - ./env/nodered.env
        network_mode: bridge
        links:
            - mosquitto:mosquitto
        ports:
            - "1880:1880"
        volumes:
            - /var/containers/vhs-smartspace/conf/nodered:/bootstrap/conf/
            - /var/containers/vhs-smartspace/data/nodered:/data

    portainer:
        image: portainer/portainer
        env_file:
            - ./env/portainer.env
        network_mode: bridge
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/containers/vhs-smartspace/data/portainer:/data

    nginx-proxy:
        image: jwilder/nginx-proxy
        network_mode: bridge
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    isvhsopen-monitor:
        image: tyisi/url-to-mqtt
        env_file:
            - ./env/isvhsopen-monitor.env
        network_mode: bridge
        links:
            - mosquitto-trust:mosquitto

    laserbusy-monitor:
        image: tyisi/url-to-mqtt
        env_file:
            - ./env/laserbusy-monitor.env
        network_mode: bridge
        links:
            - mosquitto-trust:mosquitto

    sip-monitor:
        image: tyisi/sip-to-mqtt
        env_file:
            - ./env/sip-monitor.env
        network_mode: bridge
        ports:
          - "5060:5060"
        links:
            - mosquitto-trust:mosquitto

secrets:
    grafana_admin_password:
        file: /var/containers/vhs-smartspace/secrets/grafana-admin-password
