version: "3.7"
services:
    mosquitto-hub:
        image: eclipse-mosquitto
        env_file:
            - ./env/mosquitto-hub.env
        network_mode: bridge
        volumes:
            - ./conf/mosquitto-hub/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data/mosquitto-hub:/mosquitto/data
            - ./logs/mosquitto-hub:/mosquitto/log

    mosquitto-trust:
        image: eclipse-mosquitto
        depends_on:
            - mosquitto-hub
        env_file:
            - ./env/mosquitto-trust.env
        network_mode: bridge
        links:
            - mosquitto-hub:mosquitto-hub
        ports:
            - "2883:1883"
            - "2901:9001"
        volumes:
            - ./conf/mosquitto-trust/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data/mosquitto-trust:/mosquitto/data
            - ./logs/mosquitto-trust:/mosquitto/log

    mosquitto:
        image: eclipse-mosquitto
        depends_on:
            - mosquitto-hub
        env_file:
            - ./env/mosquitto.env
        network_mode: bridge
        links:
            - mosquitto-hub:mosquitto-hub
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./conf/mosquitto/acl_file:/mosquitto/config/acl_file
            - ./data/mosquitto:/mosquitto/data
            - ./logs/mosquitto:/mosquitto/log

    grafana:
        image: grafana/grafana
        env_file:
            - ./env/grafana.env
        environment:
            - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
        network_mode: bridge
        links:
            - influxdb:influxdb
        volumes:
            - ./data/grafana:/var/lib/grafana

    homeassistant:
        image: homeassistant/home-assistant
        depends_on:
            - mosquitto
        env_file:
            - ./env/homeassistant.env
        network_mode: bridge
        links:
            - mosquitto:mosquitto
        ports:
            - "8123:8123"
        restart: always
        volumes:
            - ./data/home-assistant:/config
            - /etc/localtime:/etc/localtime:ro

    influxdb:
        image: influxdb
        env_file:
            - ./env/influxdb.env
        network_mode: bridge
        ports:
            - "8086:8086"
            - "8083:8083"
            - "2003:2003"
        volumes:
            - ./conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - ./data/influxdb:/var/lib/influxdb

    nodered:
        image: tyisi/node-red-docker-bootstrap
        depends_on:
            - mosquitto
        env_file:
            - ./env/nodered.env
        network_mode: bridge
        links:
            - mosquitto:mosquitto
        ports:
            - "1880:1880"
        volumes:
            - ./conf/nodered:/bootstrap/conf/
            - ./data/nodered:/data

    portainer:
        image: portainer/portainer
        env_file:
            - ./env/portainer.env
        network_mode: bridge
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data

    nginx-proxy:
        image: jwilder/nginx-proxy
        network_mode: bridge
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    sergeant:
        image: vanhack/smartspace-sergeant
        depends_on:
            - mosquitto-trust
        env_file:
            - ./env/sergeant.env
        network_mode: bridge
        links:
            - mosquitto-trust:mosquitto

    isvhsopen-monitor:
        image: tyisi/url-to-mqtt
        depends_on:
            - mosquitto-trust
        env_file:
            - ./env/isvhsopen-monitor.env
        network_mode: bridge
        links:
            - mosquitto-trust:mosquitto

    laserbusy-monitor:
        image: tyisi/url-to-mqtt
        depends_on:
            - mosquitto-trust
        env_file:
            - ./env/laserbusy-monitor.env
        network_mode: bridge
        links:
            - mosquitto-trust:mosquitto

    sip-monitor:
        image: tyisi/sip-to-mqtt
        depends_on:
            - mosquitto-trust
        env_file:
            - ./env/sip-monitor.env
        network_mode: bridge
        ports:
          - "5060:5060"
        links:
            - mosquitto-trust:mosquitto

    spacebus:
        image: nginx
        depends_on:
            - mosquitto
        env_file:
            - ./env/spacebus.env
        network_mode: bridge
        ports:
          - "5060:5060"
        links:
            - mosquitto:mosquitto
        volumes:
            - ./data/spacebus:/usr/share/nginx/html:ro
            - ./conf/spacebus/config.js:/usr/share/nginx/html/js/config.js:ro

secrets:
    grafana_admin_password:
        file: ./secrets/grafana-admin-password
