services:
    homeassistant:
        image: homeassistant/home-assistant
        depends_on:
            - mosquitto-trust
            - influxdb
        restart: always
        networks:
            - default
        ports:
            - 8123:8123
        env_file:
            - ./env/homeassistant.env
        volumes:
            - ./data/home-assistant:/config
            - /etc/localtime:/etc/localtime:ro
        labels:
            - traefik.enable=true
            - traefik.http.routers.hass.entryPoints=web
            - traefik.http.routers.hass.rule=Host(`hass.brain.venables.vanhack.ca`)
            - traefik.http.services.hass.loadbalancer.server.port=8123
