services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        networks:
            - default
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
