services:
    portainer:
        image: portainer/portainer
        restart: always
        networks:
            - default
        env_file:
            - ./env/portainer.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.portainer.entryPoints=web
            - traefik.http.routers.portainer.rule=Host(`portainer.brain.venables.vanhack.ca`)
