services:
    grafana:
        image: grafana/grafana:11.0.0
        depends_on:
            - influxdb
        restart: always
        networks:
            - default
        env_file:
            - ./env/grafana.env
        environment:
            - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
        secrets:
            - grafana_admin_password
        volumes:
            - ./data/grafana:/var/lib/grafana
        labels:
            - traefik.enable=true
            - traefik.http.routers.grafana.entryPoints=web
            - traefik.http.routers.grafana.rule=Host(`grafana.venables.vanhack.ca`)
