services:
    mosquitto-public:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto-public
        depends_on:
            - mosquitto-hub
        restart: always
        networks:
            - default
            - mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        env_file:
            - ./env/mosquitto-public.env
        volumes:
            - ./conf/mosquitto-public/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./conf/mosquitto-public/acl_file:/mosquitto/config/acl_file
            - ./data/mosquitto-public:/mosquitto/data
            - ./logs/mosquitto-public:/mosquitto/log
