services:
    portainer:
        image: portainer/portainer
        restart: always
        networks:
            - default
        ports:
            - 9000:9000
        env_file:
            - ./env/portainer.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
