services:
    influxdb:
        image: influxdb:2.3
        restart: always
        networks:
            - default
        ports:
            - 8086:8086
            - 8083:8083
            - 2003:2003
        env_file:
            - ./env/influxdb.env
        volumes:
            - ./conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - ./data/influxdb:/var/lib/influxdb
