services:
    nodered:
        image: tyisi/node-red-docker-bootstrap
        depends_on:
            - mosquitto-trust
        restart: always
        networks:
            - default
        env_file:
            - ./env/nodered.env
        volumes:
            - ./conf/nodered:/bootstrap/conf/
            - ./data/nodered:/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.nodered.entryPoints=web
            - traefik.http.routers.nodered.rule=Host(`nodered.smartspace.vanhack.ca`)
            - traefik.http.services.nodered.loadbalancer.server.port=1880
