services:
    isvhsopen-monitor:
        image: tyisi/url-to-mqtt
        depends_on:
            - mosquitto-trust
        restart: always
        networks:
            - default
        env_file:
            - ./env/isvhsopen-monitor.env
